/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ramir
 */
public class iniciarSesion extends javax.swing.JFrame {
    //Se invoca la instancia de la clase conexión
    conexion conectar = conexion.getInstance();
    
    /** Creates new form iniciarSesion */
    public iniciarSesion() {
        initComponents();
        //Se inicializan los componentes
        this.setLocationRelativeTo(null);
        //centraliza la ventana
        this.setTitle("INICIAR SESIÓN");
        //titulo de la ventana
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nombreUsu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        contrasenaUsu = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        iniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inicio de Sesión");

        nombreUsu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombreUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre de Usuario:");

        contrasenaUsu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");

        iniciar.setBackground(new java.awt.Color(51, 102, 255));
        iniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iniciar.setText("Iniciar Sesión");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iniciar)
                        .addGap(132, 132, 132))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(nombreUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(contrasenaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(contrasenaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(iniciar)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Se crea un método para inciar sesión en el sistema
    public void iniciarSesion(){
        //Se obtienen como entradas el nombre de ususario y la contraseña
        String pass = String.valueOf(contrasenaUsu.getPassword());
        String usuario = nombreUsu.getText();
        //mediante un capturador de error hacemos la consulta para verificar que el usuario este registrado
        try{
            //a travez de la instancia creada en la clase conexión accedemos al método para conectarnos a la base de datos 
            Connection conexion = conectar.conectar();
            //definimos la consulta que se hara para verificar los datos
            PreparedStatement stm = conexion.prepareStatement("select nombreCompleto,nombreUsuario,origen,cedula,contrasena from usuarios where nombreUsuario='"+usuario+"' and contrasena='"+pass+"'");
            //ejecutamos la consulta
            ResultSet rs = stm.executeQuery();
            
            //validamos que la consulta haya generado una respuesta correcta
            if(rs.next()){
                //comparamos los datos que ingresó el usuario con los de la base de datos para validarlos
                if (usuario.equals(rs.getString(2)) && pass.equals(rs.getString(5))){
                    //con el resultado de la consulta validado remitimos al usuario a la "fabrica" corespondiente según su lugar de origen
                    //solo podrá enviar paquetes desde la sede de su lugar de origen
                    //se compara el valor del campo de origen que trajo la consulta con las sedes que hay y se redirige a la sede que coincida 
                    if(rs.getString(3).equals("bogota")){
                        //habiendo comparado se muestra el formulario de envio de paquetes
                        new envio().setVisible(true);
                        //y se oculta el formulario de inicio de sesión
                        this.setVisible(false);
                        //como el formulario de envio está en otra clase es necesario crear un objeto para llamarlo
                        envio env = new envio();
                        /*a travez del objeto accedemos a las variables del formulario y cambiamos sus valores
                        1. variable envia: Cambia el valor vacio que tiene esta variable que corresponde al nombre de quien envia el paquete
                        2. variable origen: Cambia el valor vacio que tiene esta variable que corresponde a la ciudad de origen de quien envia el paquete 
                        3. variable transp: Cambia el valor vacio que tiene esta variable que corresponde al tipo de transporte que se usa en esa sede para enviar los paquetes
                        4. variable emple: Cambia el valor vacio que tiene esta variable que corresponde a la cantidad de empleados que usa esa sede para enviar los paquetes
                        5. variable sumini: Cambia el valor vacio que tiene esta variable que corresponde a la cantidad de dinero que se les proporciona a las empleados para los gastos(gasolina, etc)
                        */
                        env.envia.setText(rs.getString(1));//1
                        env.origen.setText(rs.getString(3));//2
                        env.transp.setText("Camion");//3
                        env.emple.setText("2");//4
                        env.sumini.setText("50000");//5
                        env.setVisible(true);
                        //hacemos visible el formulario de envio
                    }else if(rs.getString(3).equals("medellin")){
                        new envio().setVisible(true);
                        this.setVisible(false);
                        envio env = new envio();
                        env.envia.setText(rs.getString(1));
                        env.origen.setText(rs.getString(3));
                        env.transp.setText("Camioneta");
                        env.emple.setText("2");
                        env.sumini.setText("30000");
                        env.setVisible(true);
                    }else if(rs.getString(3).equals("barranquilla")){
                        new envio().setVisible(true);
                        this.setVisible(false);
                        envio env = new envio();
                        env.envia.setText(rs.getString(1));
                        env.origen.setText(rs.getString(3));
                        env.transp.setText("Camioneta");
                        env.emple.setText("2");
                        env.sumini.setText("30000");
                        env.setVisible(true);
                    }else if(rs.getString(3).equals("envigado")){
                        new envio().setVisible(true);
                        this.setVisible(false);
                        envio env = new envio();
                        env.envia.setText(rs.getString(1));
                        env.origen.setText(rs.getString(3));
                        env.transp.setText("Moto");
                        env.emple.setText("1");
                        env.sumini.setText("10000");
                        env.setVisible(true);
                    }else if(rs.getString(3).equals("apartado")){
                        new envio().setVisible(true);
                        this.setVisible(false);
                        envio env = new envio();
                        env.envia.setText(rs.getString(1));
                        env.origen.setText(rs.getString(3));
                        env.transp.setText("Moto");
                        env.emple.setText("1");
                        env.sumini.setText("10000");
                        env.setVisible(true);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Error de Acceso, Usuario No Registrado");
                //Si la consulta no encuentra el usuario ingresado mostrara este mensaje de error
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error : "+e);
        }
            
    }
    private void nombreUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        iniciarSesion();
        //Al darle click en el botón iniciar sesión ejecutamos el método iniciarSesion()
    }//GEN-LAST:event_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contrasenaUsu;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreUsu;
    // End of variables declaration//GEN-END:variables

}
